"""add user handle

Revision ID: 4b748f21595a
Revises: 1a80ed8b0a81
Create Date: 2026-05-11 15:05:22.691466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b748f21595a'
down_revision: Union[str, Sequence[str], None] = '1a80ed8b0a81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_handle', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_user_handle'), 'users', ['user_handle'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_handle'), table_name='users')
    op.drop_column('users', 'user_handle')
    # ### end Alembic commands ###
